# =============================================================================
# ML Pipeline Configuration
# Central configuration for training and inference jobs.
# =============================================================================

# -----------------------------------------------------------------------------
# Database Connection Settings
# -----------------------------------------------------------------------------
connection:
  database: "DEMAND_FORECAST_POC"         # Snowflake database name
  schema: "FORECASTING"       # Schema for data tables
  stage_artifacts: "ML_STAGE" # Internal stage for ML artifacts
  warehouse: "MMT_POC_M"      # Warehouse for SQL operations
  tag: "mmt_poc"              # Tag for tracking consumption

# -----------------------------------------------------------------------------
# Feature data
# -----------------------------------------------------------------------------
feature_table: 
  name: "DEMAND_PER_ITEM"           # Partitioned time step features
  partition_col: "Item Number Site"
  time_col: "Perform Date"
  target_col: "Actual Demand"
  test_pct: 0.1

# -----------------------------------------------------------------------------
# POC Data Generation Settings
# Used for generating synthetic test data.
# -----------------------------------------------------------------------------
poc_data:
  generate: False              # If false, expects feature_table.name already exists
  partitions: 100             # number of partitions/models to train
  timestep: "day"             # Options: second, minute, hour, day, week, month
  num_timesteps: 730          # Number of timesteps to generate
  num_features: 5             # Number of features to generate
  start_date: "2024-03-02"
  
# -----------------------------------------------------------------------------
# Training Configuration
# -----------------------------------------------------------------------------
training:
  mljob: True # if false, will run on warehouse. If true, must specify instance family and cluster size
  instance_family: "CPU_X64_S" # compute pool instance family.
  target_cluster_size: 5       # Number of worker nodes for distributed training.


# -----------------------------------------------------------------------------
# Inference Configuration
# -----------------------------------------------------------------------------
inference:
  mljob: False
  # instance_family: "CPU_X64_S" # compute pool instance family.
  # target_cluster_size: 5       # Number of worker nodes for distributed training.
