features_w_14_all = [
    'ACTUAL_DEMAND__abs_energy',
    'ACTUAL_DEMAND__absolute_maximum',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"mean"__maxlag_40"',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"median"__maxlag_40"',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"var"__maxlag_40',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"var"__maxlag_40"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_50__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__ar_coefficient__coeff_0__k_10',
    'ACTUAL_DEMAND__ar_coefficient__coeff_1__k_10',
    'ACTUAL_DEMAND__ar_coefficient__coeff_3__k_10',
    'ACTUAL_DEMAND__ar_coefficient__coeff_4__k_10',
    'ACTUAL_DEMAND__binned_entropy__max_bins_10',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.6"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.8"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.2',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.2',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.2',
    'ACTUAL_DEMAND__cid_ce__normalize_True',
    'ACTUAL_DEMAND__count_above_mean',
    'ACTUAL_DEMAND__count_below__t_0',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_0__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_10__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_10__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_10__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_11__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_11__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_11__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_11__w_5__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_12__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_12__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_12__w_5__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_13__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_13__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_13__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_13__w_5__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_14__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_14__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_14__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_14__w_5__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_1__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_2__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_3__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_4__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_6__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_7__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_7__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_8__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_8__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_8__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_9__w_10__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_9__w_20__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_9__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__energy_ratio_by_chunks__num_segments_10__segment_focus_6',
    'ACTUAL_DEMAND__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
    'ACTUAL_DEMAND__fft_aggregated__aggtype_"centroid"',
    'ACTUAL_DEMAND__fft_aggregated__aggtype_"kurtosis"',
    'ACTUAL_DEMAND__fft_aggregated__aggtype_"skew"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_0',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_0"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_1"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_14"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_15"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_2',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_2"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_3"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_4"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_8"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"abs"__coeff_9"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_10"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_11"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_12"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_13"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_14"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_16"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_17"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_22"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_24"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_25"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_27"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_5"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_6"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_7"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_8"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_9"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_10"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_11"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_12"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_13"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_14"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_15"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_16"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_17"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_18"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_19"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_22"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_23"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_24"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_25"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_3',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_3"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_4',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_4"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_5"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_6',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_6"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_7"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_8"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_9"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_0',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_0"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_1',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_1"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_11"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_12"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_13"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_14"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_15"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_16"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_2',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_2"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_26"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_27"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_28"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_29"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_3"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_30"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_31"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_4',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_4"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_5"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_6"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_7',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_7"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_8"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_9"',
    'ACTUAL_DEMAND__first_location_of_maximum',
    'ACTUAL_DEMAND__first_location_of_minimum',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.4',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.6',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.7',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.8',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.9',
    'ACTUAL_DEMAND__large_standard_deviation__r_0.25',
    'ACTUAL_DEMAND__large_standard_deviation__r_0.30000000000000004',
    'ACTUAL_DEMAND__last_location_of_maximum',
    'ACTUAL_DEMAND__last_location_of_minimum',
    'ACTUAL_DEMAND__lempel_ziv_complexity__bins_10',
    'ACTUAL_DEMAND__lempel_ziv_complexity__bins_100',
    'ACTUAL_DEMAND__lempel_ziv_complexity__bins_2',
    'ACTUAL_DEMAND__lempel_ziv_complexity__bins_3',
    'ACTUAL_DEMAND__lempel_ziv_complexity__bins_5',
    'ACTUAL_DEMAND__linear_trend__attr_"intercept"',
    'ACTUAL_DEMAND__linear_trend__attr_"rvalue"',
    'ACTUAL_DEMAND__linear_trend__attr_"slope"',
    'ACTUAL_DEMAND__maximum',
    'ACTUAL_DEMAND__mean',
    'ACTUAL_DEMAND__mean_change',
    'ACTUAL_DEMAND__mean_n_absolute_max__number_of_maxima_7',
    'ACTUAL_DEMAND__mean_second_derivative_central',
    'ACTUAL_DEMAND__number_cwt_peaks__n_5',
    'ACTUAL_DEMAND__number_peaks__n_1',
    'ACTUAL_DEMAND__quantile__q_0.3',
    'ACTUAL_DEMAND__quantile__q_0.4',
    'ACTUAL_DEMAND__quantile__q_0.6',
    'ACTUAL_DEMAND__quantile__q_0.7',
    'ACTUAL_DEMAND__quantile__q_0.8',
    'ACTUAL_DEMAND__quantile__q_0.9',
    'ACTUAL_DEMAND__ratio_beyond_r_sigma__r_1',
    'ACTUAL_DEMAND__ratio_beyond_r_sigma__r_1.5',
    'ACTUAL_DEMAND__ratio_beyond_r_sigma__r_2',
    'ACTUAL_DEMAND__ratio_value_number_to_time_series_length',
    'ACTUAL_DEMAND__root_mean_square',
    'ACTUAL_DEMAND__standard_deviation',
    'ACTUAL_DEMAND__sum_values',
    'ACTUAL_DEMAND__symmetry_looking__r_0.1',
    'ACTUAL_DEMAND__symmetry_looking__r_0.15000000000000002',
    'ACTUAL_DEMAND__variance',
    'ACTUAL_DEMAND__variation_coefficient',
]

features_prev_M_all = [
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"mean"__maxlag_40',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"var"__maxlag_40',
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"var"__maxlag_40"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"max"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_50__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__augmented_dickey_fuller__attr_"pvalue"__autolag_"AIC"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.6"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.8"',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_0__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_10__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_11__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_12__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_14__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_3__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_4__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_5__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_7__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_8__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_9__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
    'ACTUAL_DEMAND__fft_aggregated__aggtype_"skew"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_27"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_49"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_52"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_53"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_54"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_73"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_78"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_80"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_9',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_97"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_98"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_26"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_27"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_28"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_29"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_45"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_46"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_47"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_48"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_49"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_5',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_6',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_7',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_71"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_72"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_73"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_74"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_77"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_8',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_80"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_9',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_94"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_95"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_96"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_14',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_15',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_23"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_24"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_47"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_48"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_49"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_50"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_51"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_52"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_53"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_54"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_55"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_56"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_57"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_6"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_80"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_94"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_95"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_97"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_98"',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.7',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.8',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.9',
    'ACTUAL_DEMAND__last_location_of_minimum',
    'ACTUAL_DEMAND__mean_change',
    'ACTUAL_DEMAND__mean_second_derivative_central',
]

features_prev_6M_all = [
    'ACTUAL_DEMAND__agg_autocorrelation__f_agg_"var"__maxlag_40"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"rvalue"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"slope"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"min"',
    'ACTUAL_DEMAND__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"min"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.0"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.2"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.6"',
    'ACTUAL_DEMAND__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.8"',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_0__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_12__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_2__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_5__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_8__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__cwt_coefficients__coeff_9__w_2__widths_(2, 5, 10, 20)',
    'ACTUAL_DEMAND__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
    'ACTUAL_DEMAND__fft_aggregated__aggtype_"skew"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_52"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_97"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"angle"__coeff_98"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_26',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_27',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_28',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_52"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_53',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_93"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_94"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_95"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_96"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"imag"__coeff_97"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_47"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_48"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_49"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_52',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_52"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_53',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_53"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_54',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_54"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_55',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_94"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_95"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_96"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_97"',
    'ACTUAL_DEMAND__fft_coefficient__attr_"real"__coeff_98"',
    'ACTUAL_DEMAND__first_location_of_minimum',
    'ACTUAL_DEMAND__index_mass_quantile__q_0.9',
    'ACTUAL_DEMAND__last_location_of_minimum',
    'ACTUAL_DEMAND__mean_change',
    'ACTUAL_DEMAND__mean_second_derivative_central',
]
